### ISSUE TITLE
get_reg(): Return value is truncated to 16 bits

### ISSUE THREAD

**Issue by telkamp** [HonzaMat/PyOpenocdClient#24]
The return value of [get_reg()](https://github.com/HonzaMat/PyOpenocdClient/blob/1887600d626bdba284cbad9c87bb40f9350dceed/src/py_openocd_client/client.py#L336) is truncated to 16 bits:
```
        try:
            # Expecting a single hexadecimal number on the output
            return int(reg_value, 16)
            [...]
```
With 32-bit architectures, this leads to data loss. Is it really necessary to limit the return value, or could we return the return value of OpenOCD as it is?

**Comment by HonzaMat** [comment]
Hello @telkamp, 

`get_reg()` does not truncate the register values anyhow.

The number `16` in `int(reg_value, 16)` denotes the base of the input number - it says that it is a hexadecimal number. It is not related to the bit width of the result.

See the python documentation for `int()`: https://docs.python.org/3/library/functions.html#int

**Comment by telkamp** [comment]
Hello @HonzaMat,
of course you are right. The truncation was the result of an incorrect formatting instruction in my test application. That `get_reg()` could be responsible for the truncation was somehow more obvious to me ;-) Sorry for that.

Nice project by the way. I've started with the [Python openocd](https://pypi.org/project/openocd/) library, but it does not support multiple targets. I also appreciate the automatic tests that come with your project. Thank you for your support!

**Comment by HonzaMat** [comment]
Thanks for your positive feedback and I am glad you have resolved the issue.
